In [1]:
import numpy as np

# Q1: Questions on Basic NumPy Array

## (a) Reverse the NumPy array

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.flip(arr)
arr

array([5, 4, 6, 3, 2, 1])

## (b) Flatten the array

In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1.flatten()
## shares no memory

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [4]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1 = np.ravel(array1)
array1
##  shares memory 

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [5]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1=array1.reshape(1,9)
array1
## can control shape

array([[1, 2, 3, 2, 4, 5, 1, 2, 3]])

## (c) Compare the following numpy arrays

In [6]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 
arr1 == arr2

array([[ True,  True],
       [ True,  True]])

## (d) Find the most frequent value and their indice(s) in the following arrays: 


In [7]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique,counts =np.unique(x, return_counts=True)
most_freq_idx=np.argmax(counts)                                             ## index of most frequent element
most_freq_val=unique[most_freq_idx]                                         ## most frequent value
most_freq_vals_idx=np.argwhere(x == most_freq_val)                          ## indices of most frequent value
print(most_freq_vals_idx)                                                   ## print indices of most frequent value

[[0]
 [5]
 [7]
 [8]
 [9]]


In [16]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique,counts=np.unique(y,return_counts=True)
print(counts)
max_count=np.max(counts)                    ## Find the maximum count
most_freq_vals=unique[counts==max_count]    ## All most frequent values
print(most_freq_vals)

[3 2 3 2]
[1 3]


## (e) For the array, find 


### i. Sum of all elements 

In [25]:
gfg = np.matrix([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
print(gfg.sum())

45


### ii. Sum of all elements row-wise

In [24]:
gfg = np.matrix([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
print(gfg.sum(axis=1))

[[14]
 [16]
 [15]]


### iii. Sum of all elements column-wise

In [23]:
gfg = np.matrix([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
print(gfg.sum(axis=0))

[[20  9 16]]


##  (f) For the matrix: n_array, find 

### i. Sum of diagonal elements 

In [28]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(n_array.trace())
print(n_array.diagonal())

176
[55 44 77]


### ii. Eigen values of matrix 

In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.linalg.eigvals(n_array))

[98.16835147 28.097044   49.73460452]


### iii. Eigen vectors of matrix 

In [36]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
evector=np.linalg.eig(n_array)
print(evector[1])

[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


### iv. Inverse of matrix 

In [37]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
inv=np.linalg.inv(n_array)
print(inv)

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


### v. Determinant of matrix 

In [38]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
det=np.linalg.det(n_array)
print(det)

137180.0000000001


## (g) Multiply the following matrices and also find covariance between matrices using NumPy:

### i)

In [44]:
p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]] 
np.matmul(p,q)
np.cov(p,q)

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

### ii)

In [55]:
p = [[1, 2], [2, 3], [4, 5]] 
q = [[4, 5, 1], [6, 7, 2]]
np.matmul(p,q)

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

## (h) For the matrices: find inner, outer and cartesian product? 

In [65]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner Product
print(np.inner(x,y))

# Outer Product
print(np.outer(x,y))

# Cartesian Product
print(np.array(np.meshgrid(x,y)).T.reshape(-1,2))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


# Q2: Based on NumPy Mathematics and Statistics

## (a) For the array

### i. Find element-wise absolute value 

In [67]:
arr = np.array([[1, -2, 3],[-4, 5, -6]])
print(arr.__abs__()) 
print(np.abs(arr)) 

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


### ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row. 

In [68]:
arr = np.array([[1, -2, 3],[-4, 5, -6]])
arr=arr.flatten()
print(np.percentile(arr,[25,50,75]))

[-3.5 -0.5  2.5]


### iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row 

In [73]:
arr = np.array([[1, -2, 3],[-4, 5, -6]])
arr=arr.flatten()
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

-0.5
-0.5
3.8622100754188224


## (b) For the array: Find floor, ceiling and truncated value, rounded values

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


# Q3: Based on Searching and Sorting

## (a) For the array: find 

### i. Sorted array

In [78]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
arr=np.sort(arr)
print(arr)

[ 10  16  16  52  54  62 453]


### ii. Indices of sorted array 

In [82]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
arr=np.argsort(arr)
print(arr)

[0 3 4 1 5 2 6]


### iii. 4 smallest elements 

In [90]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
smallest_4=np.partition(arr,4)[:4]
print(smallest_4)

[10 16 16 52]


### iv. 5 largest elements 

In [95]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
largest_5=np.partition(arr,-5)[-5:]
print(largest_5)

[ 16  52  54  62 453]


## (b) For the array find

### i. Integer elements only 

In [102]:
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
inte=np.argwhere(arr==arr.astype(int))
print(inte)

[[0]
 [3]
 [4]
 [5]]


### ii. Float elements only 

In [104]:
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
inte=np.argwhere(arr!=arr.astype(int))
print(inte)

[[1]
 [2]]
