In [8]:
import numpy as np

# Q1: Questions on Basic NumPy Array

# (a) Reverse the NumPy array

In [19]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.flip(arr)
arr

array([5, 4, 6, 3, 2, 1])

# (b) Flatten the array

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1.flatten()
## shares no memory

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [28]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1 = np.ravel(array1)
array1
##  shares memory 

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [31]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1=array1.reshape(1,9)
array1
## can control shape

array([[1, 2, 3, 2, 4, 5, 1, 2, 3]])

# (c) Compare the following numpy arrays

In [36]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 
arr1 == arr2

array([[ True,  True],
       [ True,  True]])

# (d) Find the most frequent value and their indice(s) in the following arrays: 


In [ ]:

x = np.array([1,2,3,4,5,1,2,1,1,1])
unique,counts =np.unique(x, return_counts=True)
np.

np.int64(5)